#!/bin/bash


source "$CONFIG_DIR/colors.sh"  #loads all defined colors
 
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=38 blur_radius=30 color=$DANIELCBLUE

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5 \
  padding_right=5 \
  icon.font="Hack Nerd Font:Bold:17.0" \
  label.font="Hack Nerd Font:Bold:14.0" \
  background.color=$BLACK \
  background.corner_radius=4 \
  background.height=24 \
  icon.color=$WHITE \
  label.color=$WHITE \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.padding_left=4 \
  label.padding_right=4 \
)
sketchybar --default "${default[@]}"

sketchybar --bar blur_radius=8 \
                 position=top \
                 sticky=off \
                 pading_left=10 \
                 padding_right=10 \
                 corner_radius=15 \
                 height=38\
                 color=$SKETCHYBAR


# -- Rightside Items -- 
source $ITEM_DIR/clock.sh
#source $ITEM_DIR/controllcenter.sh funktioniert nicht :(
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh


# -- Leftside Items -- 

source $ITEM_DIR/front_app.sh
source $ITEM_DIR/spaces.sh


# --Rightside Notch --

                    
sketchybar --add event spotify_change "com.spotify.client.PlaybackStateChanged"
source $ITEM_DIR/media.sh     



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
